dApp Store Schema
merokudao/dapp-store-registry pull request #38
Opened 2023-04-05 08:22 UTC by rishikesh-y

2023-04-06 09:07 UTC, r4881t requested changes

2023-04-06 09:07 UTC, r4881t commented on src/dappStore.json
> +}
extra line at end of file required.

2023-04-06 12:18 UTC, rishikesh-y commented on src/dappStore.json
> +}
done

2023-04-06 12:38 UTC, kailash-bitpack commented on src/lib/utils.ts
> +  } else {
const file = schema === "registry" ? "src/registy.json" : "src/...."

2023-04-06 12:39 UTC, kailash-bitpack commented on src/lib/utils.ts
> +  dappIds.map(x => {
use .forEach

2023-04-06 13:08 UTC, rishikesh-y commented on src/lib/utils.ts
> +  } else {
done

2023-04-06 13:08 UTC, rishikesh-y commented on src/lib/utils.ts
> +  dappIds.map(x => {
done

2023-04-11 07:48 UTC, kailash-bitpack approved these changes

2023-04-11 08:03 UTC, merged